spring:
  application:
    name: eurekaserver

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false #Configurar para o eureka não se auto registrar
    fetch-registry: false #Não buscar os registros dos microservicos (quem vai fazer isso será o gateway)