spring:
  application:
    name: mscloudgateway
  clound:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #Estou habilitando o localizador de microservicos e vou localizar por lowercase como no aquivo Application

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka