spring:
  application:
    name: mscartoes

server:
  port: 0 # Quando eu coloco 0 ele sobe em uma porta aleatória - Ele vai gerar minhas instâncias em portas aleatórias

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring-application.instance_id:${random.value} }